// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Store$DividerEditor from "./Store.bs.js";
import * as Controls$DividerEditor from "./Controls.bs.js";
import * as SVGDisplay$DividerEditor from "./SVGDisplay.bs.js";
import * as EditorComponent$DividerEditor from "./EditorComponent.bs.js";

import './App.css';
;

function AppMain(Props) {
  var match = React.useReducer(Store$DividerEditor.reducer, Store$DividerEditor.initialState);
  var dispatch = match[1];
  var state = match[0];
  return React.createElement("div", undefined, React.createElement(Controls$DividerEditor.make, {
                  state: state,
                  dispatch: dispatch
                }), React.createElement("hr", undefined), React.createElement(EditorComponent$DividerEditor.make, {
                  state: state,
                  dispatch: dispatch
                }), React.createElement("hr", undefined), React.createElement("hr", undefined), React.createElement(SVGDisplay$DividerEditor.make, {
                  state: state,
                  dispatch: dispatch
                }), React.createElement("hr", undefined));
}

var make = AppMain;

export {
  make ,
  
}
/*  Not a pure module */
