// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Reprocessing from "reprocessing/src/Reprocessing.bs.js";
import * as Editor$RescriptReactIntro from "./Editor.bs.js";

function EditorComponent(Props) {
  var id = "divider-editor";
  React.useEffect(function () {
        Reprocessing.setScreenId(id);
        Reprocessing.run(Editor$RescriptReactIntro.setup, undefined, Editor$RescriptReactIntro.draw, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
        
      });
  return React.createElement("canvas", {
              id: id
            });
}

var make = EditorComponent;

export {
  make ,
  
}
/* react Not a pure module */
