// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Target2$DividerEditor from "./Target2.bs.js";

function Scrap(Props) {
  return React.createElement("main", undefined, React.createElement("div", {
                  className: "Scrap"
                }, React.createElement("header", {
                      className: "Scrap-header"
                    }, React.createElement("div", undefined, React.createElement("button", undefined, "Show width"), React.createElement("span", {
                              className: "width"
                            }, String(Target2$DividerEditor.getValue(undefined)))))));
}

var a = {
  hd: "a",
  tl: {
    hd: "b",
    tl: /* [] */0
  }
};

var make = Scrap;

export {
  a ,
  make ,
  
}
/* react Not a pure module */
