// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as DrawingToSVG$DividerEditor from "./DrawingToSVG.bs.js";
import * as EditorComponent$DividerEditor from "./EditorComponent.bs.js";

function SVGDisplay(Props) {
  var state = Props.state;
  return React.createElement("main", undefined, React.createElement("div", {
                  className: "SVGDisplay",
                  dangerouslySetInnerHTML: {
                    __html: DrawingToSVG$DividerEditor.dividerToSVG(DrawingToSVG$DividerEditor.drawingToDivider(state, EditorComponent$DividerEditor.getStrokes(undefined)))
                  }
                }));
}

var make = SVGDisplay;

export {
  make ,
  
}
/* react Not a pure module */
