// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as DrawingToSVG$RescriptReactIntro from "./DrawingToSVG.bs.js";
import * as EditorComponent$RescriptReactIntro from "./EditorComponent.bs.js";

function SVGDisplay(Props) {
  var state = Props.state;
  return React.createElement("main", undefined, React.createElement("div", {
                  className: "SVGDisplay"
                }, React.createElement("div", {
                      dangerouslySetInnerHTML: {
                        __html: DrawingToSVG$RescriptReactIntro.dividerToSVG(DrawingToSVG$RescriptReactIntro.drawingToDivider(state, EditorComponent$RescriptReactIntro.getStrokes(undefined)))
                      }
                    })));
}

var s = "<svg height=\"1000\" width=\"1000\">\n <rect width=\"300\" height=\"100\" style=\"fill:rgb(0,0,255);\" /> \n</svg>";

var make = SVGDisplay;

export {
  s ,
  make ,
  
}
/* react Not a pure module */
