// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Pervasives from "rescript/lib/es6/pervasives.js";
import * as DrawingToSVG$DividerEditor from "./DrawingToSVG.bs.js";
import * as EditorComponent$DividerEditor from "./EditorComponent.bs.js";

function SVGDisplay(Props) {
  var state = Props.state;
  React.useEffect(function () {
        
      });
  return React.createElement("main", undefined, React.createElement("div", {
                  className: "SVGDisplay",
                  dangerouslySetInnerHTML: {
                    __html: DrawingToSVG$DividerEditor.dividerToSVG(DrawingToSVG$DividerEditor.drawingToDivider(state, EditorComponent$DividerEditor.getStrokes(undefined)))
                  }
                }), React.createElement("p", undefined, Pervasives.string_of_bool(state.newStart)));
}

var make = SVGDisplay;

export {
  make ,
  
}
/* react Not a pure module */
